---
- hosts: 'local'
  connection: local
  vars:
    brew_packages:
      - git
      - git-secrets
      - jq
      - zsh
      - zsh-syntax-highlighting
      - anyenv
      - direnv
    brew_cask_packages:
      - alfred
      - docker
      - iterm2
      - visual-studio-code
  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"
    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
        install_options: "appdir=/Applications"
        accept_external_apps: yes
      with_items: "{{ brew_cask_packages }}"
    - name: Setup git secrets
      shell: |
        git secrets --register-aws --global
        git secrets --install ~/.git-templates/git-secrets
        git config --global init.templatedir '~/.git-templates/git-secrets'
